blank_issues_enabled: false
contact_links:
  - name: Suggestion
    url: https://github.com/sanjjaystars/Apex-linux/discussions
    about: Suggest a new feature, change to existing feature, or other ideas in Discussions.
  - name: Support
    url: https://github.com/sanjjaystars/Apex-linux/discussions
    about: Need help? Join our Discussions for support with any issues. GitHub issues should be used for verified bugs only.
