run_logged "$APEX_INSTALL/config/theme-system.sh" "System Theme Setup"
run_logged "$APEX_INSTALL/config/browser-policy.sh" "Browser Policies"
run_logged "$APEX_INSTALL/config/increase-lockout-limit.sh" "Lockout Limit Configuration"
run_logged "$APEX_INSTALL/config/lockscreen-pam.sh" "Lockscreen PAM"
run_logged "$APEX_INSTALL/config/fix-powerprofilesctl-shebang.sh" "Powerprofilesctl Shebang"
run_logged "$APEX_INSTALL/config/ssh-command-path.sh" "SSH Command PATH"
run_logged "$APEX_INSTALL/config/ssh-keepalive.sh" "SSH Keepalive"
run_logged "$APEX_INSTALL/config/docker.sh" "Docker Security"
run_logged "$APEX_INSTALL/config/snapper.sh" "Snapper Snapshots"
run_logged "$APEX_INSTALL/config/enable-services.sh" "Enable System Services"
run_logged "$APEX_INSTALL/config/firewall.sh" "Firewall Configuration"
