run_logged "$APEX_INSTALL/user/theme.sh" "User Theme Configuration"
run_logged "$APEX_INSTALL/user/chromium.sh" "User Chromium Setup"
run_logged "$APEX_INSTALL/user/git.sh" "User Git Identification"
run_logged "$APEX_INSTALL/user/xcompose.sh" "User XCompose Configuration"
run_logged "$APEX_INSTALL/user/mise-work.sh" "User Mise Work Environments"

run_logged "$APEX_INSTALL/user/hardware/asus/fix-audio-mixer.sh" "ASUS Audio Mixer"
run_logged "$APEX_INSTALL/user/hardware/asus/fix-mic.sh" "ASUS Mic Setup"
run_logged "$APEX_INSTALL/user/hardware/framework/fix-f13-amd-audio-input.sh" "Framework 13 Audio Input"
run_logged "$APEX_INSTALL/user/hardware/dell/xps13-text-scaling.sh" "Dell XPS 13 Text Scaling"
run_logged "$APEX_INSTALL/user/hardware/fix-nouveau-cursor.sh" "Nouveau Cursor Fix"
run_logged "$APEX_INSTALL/user/hardware/vm-no-animations.sh" "VM Animations Configuration"

run_logged "$APEX_INSTALL/user/default-keyring.sh" "User Default Keyring"
run_logged "$APEX_INSTALL/user/mise.sh" "User Mise Tooling"
